### ISSUE TITLE
Decision node not working correctly 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#7] opened 2019-11-10 01:40 UTC
This journey https://kademi.admin.kademi.us/funnels/b2b-incentive-email-campaign/version1/#journeyBuilder-tab

First decision node evaluates if the profiles ORG country is US, if it is, move to the US timer node.
Have tried different statements including Equal and Contains 'US'

This profile has a primary group https://kademi.admin.kademi.us/manageUsers/73925154/#summary-tab

Is linked to an ORG which has a US country https://kademi.admin.kademi.us/organisations/73914036/edit/

Is defaulting to the AU NZ timer node every time, so not sure if this is a bug of missconfig.

![image](https://user-images.githubusercontent.com/2201340/68537413-2a316480-03b7-11ea-884a-c6638b790e73.png)

**Comment by bradmac** [comment] 2019-11-10 20:07
closing as duplicate of https://github.com/Kademi/kademi-dev/issues/8164#issuecomment-552228781

**Closed by bradmac** 2019-11-10 20:07 UTC
Labels: help wanted
