### ISSUE TITLE
Store sidebar component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#66] opened 2020-12-02 00:41 UTC
This user http://kademiuifixes.admin.kademi-qa.co/manageUsers/28306462/#summary-tab
This page http://sales-incentive-example_kademiuifixes.kademi-qa.co/sales-incentive-example-ecomstore/?q=

The current side bar looks crusty and old-school.  

Looks like this:
![image](https://user-images.githubusercontent.com/2201340/100812724-d433d100-3491-11eb-8b0f-f5f7db9ab7fd.png)

Suggest we revamp this and use checkboxes.  Examples:

BAHOO https://au.boohoo.com/womens/oversized?prefn1=category&prefv1=Beachwear%7CDresses

![image](https://user-images.githubusercontent.com/2201340/100813393-5f619680-3493-11eb-97a5-8e8f6782502e.png)

Amazon https://www.amazon.com.au/b/?_encoding=UTF8&node=4913319051&bbn=4851799051&ref_=Oct_s9_apbd_odnav_hd_bw_b5ILeZP_1&pf_rd_r=EZ80GZ43D3V81G6FF7GW&pf_rd_p=3bf43c91-5d6e-526d-b9ab-152fe35cbf36&pf_rd_s=merchandised-search-10&pf_rd_t=BROWSE&pf_rd_i=4851799051

![image](https://user-images.githubusercontent.com/2201340/100813320-34774280-3493-11eb-884a-0b9f9630e442.png)

**Comment by bradmac** [comment] 2020-12-02 03:54
Will come back to this one

**Comment by bradmac** [comment] 2021-03-05 07:06
Duplicate of https://github.com/Kademi/kademi-public/issues/22

**Closed by bradmac** 2021-03-05 07:06 UTC
